export const SET_MOVIES = 'SET_MOVIES'

export const SET_DETAILS = 'SET_DETAILS'

export const SET_MOVIES_LOADING = 'SET_MOVIES_LOADING'

export const SET_DETAILS_LOADING = 'SET_DETAILS_LOADING'

export const SET_MOVIES_ERROR = 'SET_MOVIES_ERROR'

export const SET_DETAILS_ERROR = 'SET_DETAILS_ERROR'
