export const SET_WATCHLIST = 'SET_WATCHLIST'

export const SET_WATCHLIST_LOADING = 'SET_WATCHLIST_LOADING'

export const SET_WATCHLIST_ERROR = 'SET_WATCHLIST_ERROR'

export const ADD_WATCHLIST = 'ADD_WATCHLIST'

export const REMOVE_WATCHLIST = 'REMOVE_WATCHLIST'
